project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "showcase/"
    - "CNAME"

website:
  title: "Marketing Analytics for Design Decisions"
  site-url: https://madd.seas.gwu.edu/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-madd-gwu/
  description: 'Course website for the EMSE course "Exploratory Data Analysis" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://madd.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/madd_hex_sticker_square.png"
    card-style: summary
  navbar:
    title: ""
    left:
      - text: ""
        icon: house-door-fill
        href: index.html
      - text: "Select Section"
        menu:
        - text: "Fall 2021"
          href: http://madd.seas.gwu.edu/2021-Fall/
        - text: "Fall 2022"
          href: http://madd.seas.gwu.edu/2022-Fall/
        - text: "Fall 2023"
          href: http://madd.seas.gwu.edu/2023-Fall/
      - text: "Project Showcase"
        menu:
        - text: "Fall 2021"
          href: showcase/2021-fall.html
        - text: "Fall 2022"
          href: showcase/2022-fall.html
        - text: "Fall 2023"
          href: showcase/2023-fall.html
    right:
    - icon: list
      menu:
      - text: About
        icon: question-circle-fill
        href: about.qmd
      - text: License
        icon: award-fill
        href: LICENSE.qmd
      - text: Contact
        icon: envelope-fill
        href: mailto:jph@gwu.edu
      - text: Source files
        icon: github
        href: https://github.com/emse-madd-gwu/
  page-footer:
    center:
      - text: '<a href="https://madd.seas.gwu.edu/LICENSE.html">LICENSE: CC-BY-SA <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a>'

format:
  html:
    theme: cyborg
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
